### ISSUE TITLE
[insane amount of work] Have everything C++ style

### ISSUE THREAD

**Issue by aviallon** [allegroflare/allegro_flare#173]
This means no direct call to Allegro C functions, no direct access to things like `ALLEGRO_COLOR`, `ALLEGRO_BITMAP`, and so on.
Also, do not require pointers as they are _the devil_. Instead, manager pointer allocation inside wrapper class.

**Comment by MarkOates** [comment]
The main reason not to do this is that AllegroFlare is not meant to replace Allegro but work along side it.

Users should feel fine to use Allegro however they want, and drop in AllegroFlare class here or there to help them out with otherwise annoying tasks.  In some cases, AllegroFlare can take over functionality completely and no Allegro functions would be needed, but that depends on the classes that are being used and how comfortable the user is with the features of each library.
